### ISSUE TITLE
superfluous build|passing sticker

### ISSUE THREAD

**Issue by DewWisp** [iliana/iliana#1]
README.md has a Build|Passing sticker, which is not needed as there is no build

**Comment by iliana** [comment]
The "build passing" shield is a joke, and [it's okay to not understand](https://linuxwit.ch/blog/2018/12/e98e/#its-okay-to-not-understand).

**Comment by DewWisp** [comment]
> The "build passing" shield is a joke, and [it's okay to not understand](https://linuxwit.ch/blog/2018/12/e98e/#its-okay-to-not-understand).

Repositories should not contain jokes or superfluous info

**Comment by iliana** [comment]
I respect that opinion, but disagree, and this happens to be my repo, not yours.
